apiVersion: apps/v1
kind: Deployment
metadata:
  name:  todo-app
  namespace: default
  labels:
    app:  todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: amuldark/todo-app:latest
        ports:
        - containerPort: 3000
